services:

    openproject:
        image: openproject/openproject:14
        container_name: openproject        
        ports:
            - "8080:80"
        restart: unless-stopped    
        environment:
            - OPENPROJECT_SECRET_KEY_BASE=secret
            - OPENPROJECT_HOST__NAME=openproject.beloquicesar.ar:8080    # tudominio.com
            - OPENPROJECT_HTTPS=false
            - OPENPROJECT_DEFAULT__LANGUAGE=es
        volumes:
            - ./pgdata:/var/openproject/pgdata
            - ./assets:/var/openproject/assets 
